homeassistant:
  # Name of the location where Home Assistant is running
  name: Villa Walther
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_lat
  longitude: !secret home_long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: UTC
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  api_password: !secret http_password
  ssl_certificate: /home/homeassistant/dehydrated/certs/villawalther.duckdns.org/fullchain.pem
  ssl_key: /home/homeassistant/dehydrated/certs/villawalther.duckdns.org/privkey.pem
  base_url: villawalther.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:


# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg
  
# Camera
camera:
#  - platform: onvif
#    host: 192.168.2.100
#    port: 554
#    username: !secret hikvision_user
#    password: !secret hikvision_password
  - platform: mjpeg
    name: Hundhus Inne
    username: !secret dlink_user
    password: !secret dlink_password
    still_image_url: http://192.168.2.102/image.jpg
    mjpeg_url: http://192.168.2.102/video/mjpg.cgi
  - platform: mjpeg
    name: Hundgård
    mjpeg_url: http://192.168.2.100/Streaming/channels/1/preview
    port: 80
    username: !secret hikvision_user
    password: !secret hikvision_password

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

google:
  client_id: 946687458088-0bvduj9io489iudbmuoue2feb7fefevn.apps.googleusercontent.com
  client_secret: !secret google_secret
